version: '3.8'

services:
  postgres:
    image: postgres:16.0
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=VerySecretPassword
      - POSTGRES_DB=general_spider
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - scrapyd
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d mydatabase" ]
      interval: 30s
      retries: 5
      timeout: 20s
      start_period: 10s

  scrapyd:
    image: scrapyd
    restart: on-failure
    depends_on:
      - postgres
    volumes:
      - /opt/general_engine:/scrapyd:Z
      - /opt/general_engine/logs:/scrapyd/logs
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=VerySecretPassword
      - DB_NAME=general_spider
      - DASHBOARD_ADDRESS=http://general_engine_dashboard:8080
    networks:
      - scrapyd
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail http://localhost:6800/ --max-time 5 || exit 1" ]
      interval: 30s
      retries: 5
      timeout: 10s
      start_period: 10s

  general_engine_dashboard:
    image: dashboard
    restart: on-failure
    depends_on:
      - scrapyd
      - postgres
    links:
      - scrapyd
    ports:
      - "8080:8080"
    volumes:
      - /opt/general_engine/logs:/general/logs
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=VerySecretPassword
      - DB_NAME=general_spider
      - SCRAPYD_URL=http://scrapyd:6800
      - torproxy1,
    networks:
      - scrapyd

  torproxy:
    image: dperson/torproxy
    environment:
      - BW=100
    ports:
      - "8118:8118"
#    deploy:
#      mode: replicated
#      replicas: 5
    restart: always
    networks:
      - scrapyd

  torproxy-2:
    image: dperson/torproxy
    environment:
      - BW=100
    ports:
      - "8119:8118"
    #    deploy:
    #      mode: replicated
    #      replicas: 5
    restart: always
    networks:
      - scrapyd
volumes:
  scrapyd-volume:
  postgres:

networks:
  scrapyd:
