FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y git build-essential && apt-get clean

RUN git clone https://github.com/fossyy/scrapyd.git .
RUN cd scrapyd
RUN pip install --upgrade pip
RUN pip install setuptools wheel
RUN pip install -r requirements.txt
RUN pip install .

EXPOSE 6800

ENTRYPOINT ["scrapyd", "--pidfile="]